[tasks.build]
clear = true
command = "bun"
args = ["--bun", "astro", "build"]

[tasks.dev]
clear = true
command = "bun"
args = ["--bun", "astro", "dev"]

[tasks.lint]
clear = true
dependencies = ["lint-ts", "lint-scss"]

[tasks.lint-ts]
clear = true
command = "bun"
args = ["xo"]

[tasks.lint-scss]
clear = true
command = "bun"
args = ["--bun", "stylelint", "source/**/*.scss"]
